name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: '* * * 1,5,9,13,14,16,19,20,23,25,28,29 * 1,3,5,6'

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "theqee@gmail.com"
          git config --local user.name "nyancccat"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Do you bleed ?"
          git push
